name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build production
        env: 
          DENO_DIR: .deno
        run: deno task build
        
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: viteconf-example
          root: dist
          entrypoint: https://deno.land/std@0.157.0/http/file_server.ts